# Project: LinkedGradeSys
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
RES      = LinkedGradeSys_private.res
OBJ      = main.o util.o $(RES)
LINKOBJ  = main.o util.o $(RES)
LIBS     = -L"D:/workspace/dev/Dev-Cpp/TDM-GCC-64/lib" -L"D:/workspace/dev/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/workspace/dev/Dev-Cpp/TDM-GCC-64/include" -I"D:/workspace/dev/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/workspace/dev/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/workspace/dev/Dev-Cpp/TDM-GCC-64/include" -I"D:/workspace/dev/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/workspace/dev/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/workspace/dev/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = LinkedGradeSys.exe
CXXFLAGS = $(CXXINCS) -g3 -fexec-charset=gbk
CFLAGS   = $(INCS) -g3 -fexec-charset=gbk
DEL      = D:\workspace\dev\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

util.o: util.c
	$(CC) -c util.c -o util.o $(CFLAGS)

LinkedGradeSys_private.res: LinkedGradeSys_private.rc 
	$(WINDRES) -i LinkedGradeSys_private.rc --input-format=rc -o LinkedGradeSys_private.res -O coff 

